name: Create Draft Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release (draft)
        uses: softprops/turnstyle@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          draft: true
          body: |
            Draft release created for tag ${{ github.ref_name }}. The CI workflow will build and upload platform-specific assets.
