name: Build and Publish Release Assets

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Build and publish assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install zip (for packaging)
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Build release and examples
        run: cargo build --release --examples

      - id: package
        name: Package release artifacts
        run: |
          ART="release_artifacts_${GITHUB_REF_NAME}.zip"
          echo "Creating $ART"
          # include built binaries, examples source, README and CHANGELOG
          zip -r "$ART" target/release examples README.md CHANGELOG.md || true
          echo "ART=$ART" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.package.outputs.ART }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
