name: Create Draft Release on Tag

on:
  push:
    tags:
      - 'v*'

# Grant the workflow permission to write repo contents so the GITHUB_TOKEN
# can create releases. Without this the action fails with
# "Resource not accessible by integration" on some repos.
permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release (draft)
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          body: |
            Draft release created for tag ${{ github.ref_name }}. The CI workflow will build and upload platform-specific assets.
